language: node_js
node_js:
  - "10.15.0"
services:
  - postgresql
env:
  global:
    - CC_TEST_REPORTER_ID=2c21212bd01b49eb1c8bc2929951404e53824061cdaca893373da23563baadaf
before_script:
  - yarn global add nyc
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
 

script:
  - npm test
  
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

after_success: 
  - npm run coveralls
  - npm run coverage
  - npm run showcoverage

notifications:
  email: true

