export default {
  validInput1: {
    firstname: 'Bruce',
    lastname: 'Banner',
    othername: 'john',
    email: 'emeisksmusa@yahoo.com',
    password: 'bruce banner',
    phonenumber: '08093056052',
    passporturl: 'chuks.jpeg',
    isAdmin: 'false',
    registered: 'Date.now()',
    updated: 'Date.now()',
  },
  validInput2: {
    firstname: 'Simeon',
    lastname: 'Owen',
    othername: 'johns',
    email: 'mkwees@ytedx.com',
    password: 'chuks9mike',
    passporturl: 'johns.jpeg',
    phonenumber: '07064566559',
  },
  invalidFirstname1: {
    lastname: 'Owen',
    othernames: 'johns',
    email: 'mk@yahoo.com',
    password: 'chuks mike',
    phonenumber: '07068566559',
    passporturl: 'owenjohn.jpeg',
  },
  invalidFirstname2: {
    firstname: 93,
    lastname: 'Owen',
    othernames: 'johns',
    email: 'mk@yahoo.com',
    password: 'chuks mike',
    phonenumber: '07068566559',
    passporturl: 'owen.png',
  },
  invalidLastname1: {
    firstname: 'Chibuzor',
    othernames: 'johns',
    email: 'mk@yahoo.com',
    password: 'chuks mike',
    phonenumber: '07068566559',
    passporturl: 'buzo.png',
  },
  invalidLastname2: {
    firstname: 'Chibuzor',
    lastname: 99,
    othernames: 'johns',
    email: 'mk@yahoo.com',
    password: 'chuks mike',
    phonenumber: '07068566559',
    passporturl: 'buzwen.png',
  },
  invalidEmail1: {
    firstname: 'Chibuzor',
    lastname: 'Onyeka',
    password: 'loisnwa',
    othernames: 'johns',
    phonenumber: '07068566559',
    passporturl: 'buzwen.png',
  },
  invalidEmail2: {
    firstname: 'Chibuzor',
    lastname: 'Onyeka',
    othernames: 'johns',
    email: 'mk@yahoo',
    password: 'hy39927',
    phonenumber: '07068566559',
    passporturl: 'buzwen.png',
  },
  invalidPassword1: {
    firstname: 'Chibuzor',
    lastname: 'Onyeka',
    othernames: 'johns',
    email: 'mk@yahoo.com',
    phonenumber: '07068566559',
    passporturl: 'buzwen.png',
  },
  invalidPassword2: {
    firstname: 'Chibuzor',
    lastname: 'Onyeka',
    othernames: 'johns',
    email: 'mk@yahoo.com',
    password: '344[]',
    phonenumber: '07068566559',
    passporturl: 'buzwen.png',
  },
  invalidPassword3: {
    firstname: 'Chibuzor',
    lastname: 'Onyeka',
    othernames: 'johns',
    email: 'mk@yahoo.com',
    password: 'l06y',
    phonenumber: '07068566559',
    passporturl: 'buzwen.png',
  },
  invalidPassport1: {
    firstname: 'Chibuzor',
    lastname: 'Onyeka',
    othernames: 'johns',
    email: 'mk@yahoo.com',
    password: 'l06y98',
    phonenumber: '07068566559',
  },
  invalidPassport2: {
    firstname: 'Chibuzor',
    lastname: 'Onyeka',
    othernames: 'johns',
    email: 'mk@yahoo.com',
    password: 'l06y28h',
    phonenumber: '07068566559',
    passporturl: '',
  },
  invalidPassport3: {
    firstname: 'Chibuzor',
    lastname: 'Onyeka',
    othernames: 'johns',
    email: 'mk@yahoo.com',
    password: 'l06ysde',
    phonenumber: '07068566559',
    passporturl: 'buzwen',
  },
  emptyData: {
    firstname: '',
    lastname: '',
    email: '',
    password: '',
    phonenumber: '',
    passporturl: '',
  },
  userOneLogin: {
    firstname: 'frank', lastname: 'joy', othername: 'peter', email: 'amaechichuks20@yahoo.com', password: 'fabulous26', phonenumber: '07065768675', passporturl: 'chuks.jpeg',
  },
  userTwoLogin: {
    firstname: 'chuks',
    lastname: 'mike',
    othername: 'frank',
    email: 'mikel@yahoo.com',
    password: 'chuks mike',
    phonenumber: '07068566000',
    passporturl: 'chuksmike.jpeg',
  },
  adminLogin: { email: 'amaechichuks2000@yahoo.com.com', password: 'fabulous26' },
  emptyLoginData: { email: '', password: '' },
  noEmail: { email: '', password: 'bruce banner' },
  noPassword: { email: 'mk@yahoo.com', password: '' },
  invalidEmail: { email: 'wrongEmail', password: 'bruce banner' },
  invalidPassword: { email: 'Bruce Banner', password: 'wrongPassword' },
  invalidEmailPassword: { email: '', password: '' },
};
