export default {
  validInput1: {
    firstName: 'Bruce',
    lastName: 'Banner',
    otherName: 'john',
    email: 'emeisksmusa@yahoo.com',
    password: 'bruce banner',
    phoneNumber: '08093056052',
    isadmin: 'false',
    registered: 'Date.now()',
    updated: 'Date.now()',
  },
  validInput2: {
    firstName: 'Simeon',
    lastName: 'Owen',
    otherName: 'johns',
    email: 'mkwees@ytedx.com',
    password: 'chuks9mike',
    phoneNumber: '07064566559',
  },
  invalidfirstName1: {
    lastName: 'Owen',
    otherNames: 'johns',
    email: 'mk@yahoo.com',
    password: 'chuks mike',
    phoneNumber: '07068566559',
  },
  invalidfirstName2: {
    firstName: 93,
    lastName: 'Owen',
    otherNames: 'johns',
    email: 'mk@yahoo.com',
    password: 'chuks mike',
    phoneNumber: '07068566559',
  },
  invalidlastName1: {
    firstName: 'Chibuzor',
    otherNames: 'johns',
    email: 'mk@yahoo.com',
    password: 'chuks mike',
    phoneNumber: '07068566559',
  },
  invalidlastName2: {
    firstName: 'Chibuzor',
    lastName: 99,
    otherNames: 'johns',
    email: 'mk@yahoo.com',
    password: 'chuks mike',
    phoneNumber: '07068566559',
  },
  invalidEmail1: {
    firstName: 'Chibuzor',
    lastName: 'Onyeka',
    password: 'loisnwa',
    otherNames: 'johns',
    phoneNumber: '07068566559',
  },
  invalidEmail2: {
    firstName: 'Chibuzor',
    lastName: 'Onyeka',
    otherNames: 'johns',
    email: 'mk@yahoo',
    password: 'hy39927',
    phoneNumber: '07068566559',
  },
  invalidPassword1: {
    firstName: 'Chibuzor',
    lastName: 'Onyeka',
    otherNames: 'johns',
    email: 'mk@yahoo.com',
    phoneNumber: '07068566559',
  },
  invalidPassword2: {
    firstName: 'Chibuzor',
    lastName: 'Onyeka',
    otherNames: 'johns',
    email: 'mk@yahoo.com',
    password: '344[]',
    phoneNumber: '07068566559',
  },
  invalidPassword3: {
    firstName: 'Chibuzor',
    lastName: 'Onyeka',
    otherNames: 'johns',
    email: 'mk@yahoo.com',
    password: 'l06y',
    phoneNumber: '07068566559',
  },
  invalidPassport1: {
    firstName: 'Chibuzor',
    lastName: 'Onyeka',
    otherNames: 'johns',
    email: 'mk@yahoo.com',
    password: 'l06y98',
    phoneNumber: '07068566559',
  },
  invalidPassport2: {
    firstName: 'Chibuzor',
    lastName: 'Onyeka',
    otherNames: 'johns',
    email: 'mk@yahoo.com',
    password: 'l06y28h',
    phoneNumber: '07068566559',
  },
  invalidPassport3: {
    firstName: 'Chibuzor',
    lastName: 'Onyeka',
    otherNames: 'johns',
    email: 'mk@yahoo.com',
    password: 'l06ysde',
    phoneNumber: '07068566559',
  },
  emptyData: {
    firstName: '',
    lastName: '',
    email: '',
    password: '',
    phoneNumber: '',
  },
  userOneLogin: {
    firstName: 'frank', lastName: 'joy', otherName: 'peter', email: 'amaechichuks20@yahoo.com', password: 'fabulous26', phoneNumber: '07065768675',
  },
  userTwoLogin: {
    firstName: 'chuks',
    lastName: 'mike',
    otherName: 'frank',
    email: 'mikel@yahoo.com',
    password: 'chuks mike',
    phoneNumber: '07068566000',
  },
  adminLogin: { email: 'amaechichuks2000@yahoo.com.com', password: 'fabulous26' },
  emptyLoginData: { email: '', password: '' },
  noEmail: { email: '', password: 'bruce banner' },
  noPassword: { email: 'mk@yahoo.com', password: '' },
  invalidEmail: { email: 'wrongEmail', password: 'bruce banner' },
  invalidPassword: { email: 'Bruce Banner', password: 'wrongPassword' },
  invalidEmailPassword: { email: '', password: '' },
};
